
CREATE TABLE IF NOT EXISTS DELTA_TRAINING.EMPL_PT_36HR_FLAG(WEEK_DT TIMESTAMP,
EMPLOYEE_ID INT,
LOCATION_ID INT,
EMPL_13WK_AVG_HRS_WORKED INT,
FLAG INT,
LOAD_TSTMP TIMESTAMP) USING DELTA;

CREATE TABLE IF NOT EXISTS DELTA_TRAINING.EMPL_36HR_FLAG(WEEK_DT TIMESTAMP,
EMPLOYEE_ID INT,
LOCATION_ID INT,
EMPL_13WK_AVG_HRS_WORKED INT,
FLAG INT,
LOAD_TSTMP TIMESTAMP) USING DELTA;